name: Deploy to Vercel

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  VERCEL_ORG_ID: team_tH9RWT1FcEtTJMq8jNbXQmbg
  VERCEL_PROJECT_ID: prj_I5VCt21qTMou4HLelSBr8ShE7ejd

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: ./platform/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm
      - name: Build Project Artifacts
        run: vercel build --prod --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm

  Deploy-Preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./platform/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm
      - name: Build Project Artifacts
        run: vercel build --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=vcp_8AqnZRPqjJ1SGBUAPcHsKwRZwbRpJSzy4bS6m2hkhX1p4GprOr4aj0Hm
